apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kyverno-platform
  namespace: argocd
spec:
  description: GitOps boundary for Kyverno controller and policies
  sourceRepos:
    - https://kyverno.github.io/kyverno/
    - https://github.com/curioos/Jerney.git
  destinations:
    - namespace: kyverno
      server: https://kubernetes.default.svc
    - namespace: jerney
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"