apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: kyverno-platform
  source:
    repoURL: https://github.com/curioos/Jerney.git
    targetRevision: devops
    path: k8s/platform/kyverno
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: jerney
  syncPolicy:
    automated:
      prune: true
      selfHeal: true