          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
          image: ghcr.io/curioos/jerney/jerney-frontend:b5ac5e4
