apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jerney-backend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - jerney
  selector:
    matchLabels:
      app.kubernetes.io/name: jerney-backend
  endpoints:
    - port: http-api
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
