installCRDs: true

serviceAccount:
  create: true
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::684124087112:role/JerneyExternalSecretsIRSA

webhook:
  create: true

certController:
  create: true