apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jerney-db-secret
  namespace: jerney
  labels:
    app.kubernetes.io/name: jerney-db-secret
    app.kubernetes.io/part-of: jerney
    app.kubernetes.io/component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: jerney-db-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: jerney/prod/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: jerney/prod/postgres
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: jerney/prod/postgres
        property: database