apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jerney-backend-secret
  namespace: jerney
  labels:
    app.kubernetes.io/name: jerney-backend-secret
    app.kubernetes.io/part-of: jerney
    app.kubernetes.io/component: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: jerney-backend-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: jerney/dev/backend
        property: jwt_secret
